fix user welcome email
rero/sonar pull request #703
Opened 2021-11-10 13:05 UTC by rerowep

## Why are you opening this PR?

- Closes #684

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2021-11-18 05:50 UTC, mmo requested changes

2021-11-18 05:50 UTC, mmo commented on sonar/modules/users/utils.py
> +    plain_platform_name = 'Sonar'
```suggestion
    plain_platform_name = 'SONAR'
```

2021-11-18 06:03 UTC, mmo requested changes

2021-11-18 06:03 UTC, mmo commented on sonar/modules/users/utils.py
> +        f'{_("Welcome to")} {platform_name}',
Should use the variable `plain_platform_name` instead.

2021-11-18 06:05 UTC, mmo commented
The title of the email is currently:

> Welcome to None

"None" should be replaced by either "SONAR", for shared repositories, or by the platform name for dedicated repositories.

2021-11-29 05:32 UTC, Garfield-fr approved these changes

2021-12-02 09:15 UTC, mmo approved these changes

2021-12-02 09:35 UTC, merged