schema: distinguish supervisor co-supervisors
rero/sonar pull request #745
Opened 2021-12-22 10:55 UTC by rerowep

* Distinguish between thesis supervisor and co-supervisors
* Adds dgc "Degree committee member" for field contribution.role in document and deposit.
* Closes #733

Co-Authored-by: Peter Weber <peter.weber@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2021-12-22 11:12 UTC, Garfield-fr approved these changes

2021-12-22 12:04 UTC, pronguen approved these changes

2022-01-26 06:53 UTC, mmo commented
This line https://github.com/rero/sonar/blob/2422b8515c9d079c98921509559b438ca70c6fa3/sonar/modules/documents/views.py#L220 should be updated to:

```
    priorities = ['cre', 'ctb', 'dgs', 'dgc', 'edt', 'prt']
```

2022-01-26 06:54 UTC, mmo requested changes
This line https://github.com/rero/sonar/blob/2422b8515c9d079c98921509559b438ca70c6fa3/sonar/modules/documents/views.py#L220 should be updated to:

```
    priorities = ['cre', 'ctb', 'dgs', 'dgc', 'edt', 'prt']
```

2022-01-26 07:47 UTC, rerowep commented
> priorities = ['cre', 'ctb', 'dgs', 'dgc', 'edt', 'prt']

Changed it.

2022-02-02 10:15 UTC, merged