help: display with the organization's code
rero/sonar pull request #747
Opened 2022-01-17 13:38 UTC by Garfield-fr

The help is displayed with the organization's code
and is no longer directed to the global help.

* Closes #709.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## How to test?

- Url for organization help: https://sonar/{view}/help

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2022-01-18 10:47 UTC, jma requested changes

2022-01-18 10:47 UTC, jma commented on sonar/dedicated/__init__.py
> +# Copyright (C) 2021 RERO
2022?

2022-01-18 10:47 UTC, jma commented on sonar/help/templates/help/page_wiki_base.html
> +{# -*- coding: utf-8 -*-
Why not using the existing template `sonar/page_wiki.html`?

2022-01-18 10:47 UTC, jma commented on sonar/help/templates/help/page_wiki_base.html
> +
Javascript block seems missing.

2022-01-18 10:47 UTC, jma commented on sonar/help/templates/help/page_wiki_org.html
> +          {{ page.body.replace('](/', '](/{view}/'.format(view=view))|markdown_filter|safe }}
Is it really safe? Maybe we can replace only the `/help` links?

2022-01-18 10:47 UTC, jma commented on sonar/help/templates/help/page_wiki_search.html
> +                                <a class="mr-2" href="{{ url_for('help.page', view=view, url=result.url) }}">
I imagine this is the only modification done form flask-wiki. We can perhaps create a link factory for this?

2022-01-18 10:47 UTC, jma commented on sonar/help/views.py
> +@blueprint.route('/<org_code:view>/help/<path:url>/', methods=['GET'])
Please remove the trailing '/'.

2022-01-18 11:20 UTC, rerowep commented
We are in 2022 new, do we have to change the copyright date in the changed file?

2022-01-24 07:44 UTC, jma approved these changes

2022-01-25 17:03 UTC, pronguen commented
It works if we have the link.
But there is a default link "Aide et documentation" in sonardev, which always redirects on the global help (see screenshot). Is it possible to have the default link on the help with organisation view?
![image](https://user-images.githubusercontent.com/8154915/151023852-48eebcf9-cf3b-43a7-af35-16f469df8dbd.png)

2022-01-26 06:56 UTC, mmo approved these changes

2022-02-01 10:21 UTC, merged