swisscovery: remove << and >> characters in the title when importing
rero/sonar pull request #781
Opened 2022-02-16 10:14 UTC by Garfield-fr

* Closes #701.

Co-Authored-by: Bertrand Zuchuat <bertrand.zuchuat@rero.ch>

## How to test?

- Add a deposit and import source swisscovery with identifier: 2070406237

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2022-02-22 07:30 UTC, jma approved these changes

2022-02-22 07:30 UTC, jma commented on sonar/modules/swisscovery/rest.py
> +    if 'title' in record:
You can write something like:
```python
for title in record.get('title',[]):
    for mainTitle in title.get('mainTitle', []):
        ....
```

2022-02-22 07:30 UTC, jma commented on tests/api/swisscovery/test_swisscovery_rest.py
> +    res = client.get(url_for('swisscovery.get_record',query='2070406237'))
space is missing

2022-02-24 11:15 UTC, pronguen approved these changes

2022-02-24 12:37 UTC, rerowep requested changes

2022-02-24 12:37 UTC, rerowep commented on sonar/modules/swisscovery/rest.py
> +    # Remove << and >> in the title value
The command or function is not correct. The regexp removes all `<< ??? >>>`!

2022-02-24 13:21 UTC, rerowep approved these changes

2022-02-28 14:24 UTC, mmo approved these changes

2022-03-01 05:26 UTC, merged