documents: adapts RERO DOC import for USI publications
rero/sonar pull request #825
Opened 2022-04-13 08:27 UTC by mmo

* Adds USI-specific data transformations.
* Applies the appropriate document type for advanced studies theses.
* Fixes edition statement import (MARC field 250).
* Fixes content note import (MARC field 505).
* Fixes co-supervisor import (in MARC field 700).
* Closes #736.

Co-Authored-by: Miguel Moreira <miguel.moreira@rero.ch>

2022-04-13 08:53 UTC, Garfield-fr approved these changes

2022-04-19 07:10 UTC, jma requested changes

2022-04-19 07:10 UTC, jma commented on sonar/modules/documents/dojson/rerodoc/overdo.py
> +        if role_700 == 'Dir.':
It would be better to use a dict mapping here.

2022-04-19 07:10 UTC, jma commented on sonar/modules/documents/dojson/rerodoc/model.py
>  def marc21_to_content_note(self, key, value):
You can probably use: https://github.com/inveniosoftware/dojson/blob/5093f4d6bb15654d98af3edfa5367b4a84e5a45b/dojson/utils.py#L46

2022-04-19 07:10 UTC, jma commented on sonar/modules/documents/dojson/rerodoc/model.py
> +        if len(numbering) > 1 and numbering[1]:
You can probably use `numbering.pop()`.

2022-04-19 07:10 UTC, jma commented on sonar/modules/documents/dojson/rerodoc/model.py
> +        # Numbering year
How is it possible?

2023-05-31 02:42 UTC, closed without merging