update flask-wiki to 0.2.1
rero/sonar pull request #869
Opened 2022-07-18 06:07 UTC by PascalRepond

* Updates flask-wiki to latest version
* Removes container in wiki template to use full width of the page

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

## Why are you opening this PR?

- Which task/US does it implement?
- Which issue does it fix?

## How to test?

- What command should I have to run to test your PR?
- What should I test through the UI?

## Code review check list

- [ ] Commit message template compliance.
- [ ] Commit message without typos.
- [ ] File names.
- [ ] Functions names.
- [ ] Functions docstrings.
- [ ] Unnecessary commited files?
- [ ] Extracted translations?

2022-07-19 04:48 UTC, Garfield-fr requested changes
It's not a good structure to read. Please add le content in a new page and include this.

2022-07-25 06:58 UTC, jma requested changes

2022-07-25 06:58 UTC, jma commented on sonar/theme/templates/sonar/page.html
> +  {% block container %}<div class="container my-5">{% endblock container %}
This `div` is never closed. I do not understand what you are trying to do.

2022-07-25 06:58 UTC, jma commented on poetry.lock
> +babel = ">=2.9.1"
All dependencies has been updated. You probably edit the pyproject file by hand instead of using the `poetry` command.

2022-07-25 09:33 UTC, Garfield-fr approved these changes

2022-07-27 06:36 UTC, vgranata approved these changes

2022-08-09 06:05 UTC, BadrAly approved these changes

2022-08-10 06:28 UTC, jma approved these changes

2022-08-12 07:12 UTC, merged