jsonschemas: add 2 new document types
rero/sonar pull request #887
Opened 2022-08-18 14:55 UTC by PascalRepond

* Adds conference object and book review document types for documents
and deposits.
* Changes value and label for document_type_other for better clarity.
* Initializes alembic.
* Includes alembic script for db migration.
* Closes #881.
* Closes #626.
* Makes the `status` deposit field required to prevent submitting
a deposit with no status from the API.

Co-Authored-by: Pascal Repond <pascal.repond@rero.ch>

2022-08-18 14:59 UTC, zannkukai approved these changes

2022-08-23 11:45 UTC, jma approved these changes

2022-08-25 06:48 UTC, pronguen requested changes
2 problems regarding https://github.com/rero/sonar/issues/881

2022-08-25 06:48 UTC, pronguen commented on sonar/modules/documents/serializers/schemas/schemaorg.py
>      'other': 'Thesis',
```suggestion
    'other_thesis': 'Thesis',
```

2022-08-25 06:51 UTC, PascalRepond commented on sonar/modules/deposits/jsonschemas/deposits/deposit-v1.0.0_src.json
> +                "hideExpression": "field.parent.parent.model && !['coar:c_3248', 'coar:c_3e5a', 'coar:c_ba08', coar:c_beb9', 'coar:c_6501', 'coar:c_998f', 'coar:c_dcae04bc', 'coar:c_816b', 'coar:c_57
Oops, bien vu!

2022-08-25 06:51 UTC, PascalRepond commented on sonar/modules/documents/serializers/schemas/schemaorg.py
>      'other': 'Thesis',
Re-bien vu! Merci

2022-08-25 06:57 UTC, pronguen commented
*[work in progress...]*

Problems regarding https://github.com/rero/sonar/issues/626

- [ ] Field "numberingVolume" (document) still not available for the specified document types
![image](https://user-images.githubusercontent.com/8154915/186595983-31342a23-384e-4381-a251-1390b5441bdf.png)

2022-08-25 14:28 UTC, merged